package main

import (
	"fmt"
	"github.com/pion/mediadevices/pkg/codec/openh264"
	signal "github.com/qiulin/mediadevices-windows-cameras/singal"
	"log/slog"

	"github.com/pion/mediadevices"
	"github.com/pion/mediadevices/pkg/frame"
	"github.com/pion/mediadevices/pkg/prop"
	"github.com/pion/webrtc/v3"

	// If you don't like x264, you can also use vpx by importing as below
	// "github.com/pion/mediadevices/pkg/codec/vpx" // This is required to use VP8/VP9 video encoder
	// or you can also use openh264 for alternative h264 implementation
	// "github.com/pion/mediadevices/pkg/codec/openh264"
	// or if you use a raspberry pi like, you can use mmal for using its hardware encoder
	// "github.com/pion/mediadevices/pkg/codec/mmal"
	"github.com/pion/mediadevices/pkg/codec/opus" // This is required to use opus audio encoder
	// Note: If you don't have a camera or microphone or your adapters are not supported,
	//       you can always swap your adapters with our dummy adapters below.
	// _ "github.com/pion/mediadevices/pkg/driver/videotest"
	// _ "github.com/pion/mediadevices/pkg/driver/audiotest"
	_ "github.com/pion/mediadevices/pkg/driver/camera"     // This is required to register camera adapter
	_ "github.com/pion/mediadevices/pkg/driver/microphone" // This is required to register microphone adapter
)

func main() {
	logger := slog.Default()
	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	}
	logger.Info("load config")

	// Wait for the offer to be pasted
	offer := webrtc.SessionDescription{}
	sd := `eyJ0eXBlIjoib2ZmZXIiLCJzZHAiOiJ2PTBcclxubz0tIDU4NTk3NzEyNDk4Njk5Mjg1MTUgMiBJTiBJUDQgMTI3LjAuMC4xXHJcbnM9LVxyXG50PTAgMFxyXG5hPWdyb3VwOkJVTkRMRSAwIDFcclxuYT1leHRtYXAtYWxsb3ctbWl4ZWRcclxuYT1tc2lkLXNlbWFudGljOiBXTVNcclxubT1hdWRpbyA5IFVEUC9UTFMvUlRQL1NBVlBGIDExMSA2MyA5IDAgOCAxMyAxMTAgMTI2XHJcbmM9SU4gSVA0IDAuMC4wLjBcclxuYT1ydGNwOjkgSU4gSVA0IDAuMC4wLjBcclxuYT1jYW5kaWRhdGU6Nzk3MTMyNjU1IDEgdWRwIDIxMTM5MzcxNTEgNWQ0ODM5MzctNTA4Mi00MDVkLWI0OTEtZGU3MWM2MWUzNGQwLmxvY2FsIDU2NTUxIHR5cCBob3N0IGdlbmVyYXRpb24gMCBuZXR3b3JrLWNvc3QgOTk5XHJcbmE9aWNlLXVmcmFnOmtuMktcclxuYT1pY2UtcHdkOlVQUGt5d0VHMjRGUEEvOTkwRXhDTXRQcVxyXG5hPWljZS1vcHRpb25zOnRyaWNrbGVcclxuYT1maW5nZXJwcmludDpzaGEtMjU2IDAyOjM2OkM2OjAzOjI2OkUzOjZFOjhGOjIzOjE0Ojg5OjE0OkJDOkMyOkFBOjIwOjI3OkY1OjQ0OjUzOjREOkUxOjIzOjBGOkMyOjkwOjI4OkU1OjNGOjc4OjYwOjAwXHJcbmE9c2V0dXA6YWN0cGFzc1xyXG5hPW1pZDowXHJcbmE9ZXh0bWFwOjEgdXJuOmlldGY6cGFyYW1zOnJ0cC1oZHJleHQ6c3NyYy1hdWRpby1sZXZlbFxyXG5hPWV4dG1hcDoyIGh0dHA6Ly93d3cud2VicnRjLm9yZy9leHBlcmltZW50cy9ydHAtaGRyZXh0L2Ficy1zZW5kLXRpbWVcclxuYT1leHRtYXA6MyBodHRwOi8vd3d3LmlldGYub3JnL2lkL2RyYWZ0LWhvbG1lci1ybWNhdC10cmFuc3BvcnQtd2lkZS1jYy1leHRlbnNpb25zLTAxXHJcbmE9ZXh0bWFwOjQgdXJuOmlldGY6cGFyYW1zOnJ0cC1oZHJleHQ6c2RlczptaWRcclxuYT1yZWN2b25seVxyXG5hPXJ0Y3AtbXV4XHJcbmE9cnRwbWFwOjExMSBvcHVzLzQ4MDAwLzJcclxuYT1ydGNwLWZiOjExMSB0cmFuc3BvcnQtY2NcclxuYT1mbXRwOjExMSBtaW5wdGltZT0xMDt1c2VpbmJhbmRmZWM9MVxyXG5hPXJ0cG1hcDo2MyByZWQvNDgwMDAvMlxyXG5hPWZtdHA6NjMgMTExLzExMVxyXG5hPXJ0cG1hcDo5IEc3MjIvODAwMFxyXG5hPXJ0cG1hcDowIFBDTVUvODAwMFxyXG5hPXJ0cG1hcDo4IFBDTUEvODAwMFxyXG5hPXJ0cG1hcDoxMyBDTi84MDAwXHJcbmE9cnRwbWFwOjExMCB0ZWxlcGhvbmUtZXZlbnQvNDgwMDBcclxuYT1ydHBtYXA6MTI2IHRlbGVwaG9uZS1ldmVudC84MDAwXHJcbm09dmlkZW8gOSBVRFAvVExTL1JUUC9TQVZQRiA5NiA5NyA5OCA5OSAxMDAgMTAxIDM1IDM2IDM3IDM4IDEwMiAxMDMgMTA0IDEwNSAxMDYgMTA3IDEwOCAxMDkgMTI3IDEyNSAzOSA0MCA0MSA0MiA0MyA0NCA0NSA0NiA0NyA0OCAxMTIgMTEzIDExNCAxMTUgMTE2IDExNyAxMTggNDlcclxuYz1JTiBJUDQgMC4wLjAuMFxyXG5hPXJ0Y3A6OSBJTiBJUDQgMC4wLjAuMFxyXG5hPWNhbmRpZGF0ZTo3OTcxMzI2NTUgMSB1ZHAgMjExMzkzNzE1MSA1ZDQ4MzkzNy01MDgyLTQwNWQtYjQ5MS1kZTcxYzYxZTM0ZDAubG9jYWwgNTY1NTMgdHlwIGhvc3QgZ2VuZXJhdGlvbiAwIG5ldHdvcmstY29zdCA5OTlcclxuYT1pY2UtdWZyYWc6a24yS1xyXG5hPWljZS1wd2Q6VVBQa3l3RUcyNEZQQS85OTBFeENNdFBxXHJcbmE9aWNlLW9wdGlvbnM6dHJpY2tsZVxyXG5hPWZpbmdlcnByaW50OnNoYS0yNTYgMDI6MzY6QzY6MDM6MjY6RTM6NkU6OEY6MjM6MTQ6ODk6MTQ6QkM6QzI6QUE6MjA6Mjc6RjU6NDQ6NTM6NEQ6RTE6MjM6MEY6QzI6OTA6Mjg6RTU6M0Y6Nzg6NjA6MDBcclxuYT1zZXR1cDphY3RwYXNzXHJcbmE9bWlkOjFcclxuYT1leHRtYXA6MTQgdXJuOmlldGY6cGFyYW1zOnJ0cC1oZHJleHQ6dG9mZnNldFxyXG5hPWV4dG1hcDoyIGh0dHA6Ly93d3cud2VicnRjLm9yZy9leHBlcmltZW50cy9ydHAtaGRyZXh0L2Ficy1zZW5kLXRpbWVcclxuYT1leHRtYXA6MTMgdXJuOjNncHA6dmlkZW8tb3JpZW50YXRpb25cclxuYT1leHRtYXA6MyBodHRwOi8vd3d3LmlldGYub3JnL2lkL2RyYWZ0LWhvbG1lci1ybWNhdC10cmFuc3BvcnQtd2lkZS1jYy1leHRlbnNpb25zLTAxXHJcbmE9ZXh0bWFwOjUgaHR0cDovL3d3dy53ZWJydGMub3JnL2V4cGVyaW1lbnRzL3J0cC1oZHJleHQvcGxheW91dC1kZWxheVxyXG5hPWV4dG1hcDo2IGh0dHA6Ly93d3cud2VicnRjLm9yZy9leHBlcmltZW50cy9ydHAtaGRyZXh0L3ZpZGVvLWNvbnRlbnQtdHlwZVxyXG5hPWV4dG1hcDo3IGh0dHA6Ly93d3cud2VicnRjLm9yZy9leHBlcmltZW50cy9ydHAtaGRyZXh0L3ZpZGVvLXRpbWluZ1xyXG5hPWV4dG1hcDo4IGh0dHA6Ly93d3cud2VicnRjLm9yZy9leHBlcmltZW50cy9ydHAtaGRyZXh0L2NvbG9yLXNwYWNlXHJcbmE9ZXh0bWFwOjQgdXJuOmlldGY6cGFyYW1zOnJ0cC1oZHJleHQ6c2RlczptaWRcclxuYT1leHRtYXA6MTAgdXJuOmlldGY6cGFyYW1zOnJ0cC1oZHJleHQ6c2RlczpydHAtc3RyZWFtLWlkXHJcbmE9ZXh0bWFwOjExIHVybjppZXRmOnBhcmFtczpydHAtaGRyZXh0OnNkZXM6cmVwYWlyZWQtcnRwLXN0cmVhbS1pZFxyXG5hPXJlY3Zvbmx5XHJcbmE9cnRjcC1tdXhcclxuYT1ydGNwLXJzaXplXHJcbmE9cnRwbWFwOjk2IFZQOC85MDAwMFxyXG5hPXJ0Y3AtZmI6OTYgZ29vZy1yZW1iXHJcbmE9cnRjcC1mYjo5NiB0cmFuc3BvcnQtY2NcclxuYT1ydGNwLWZiOjk2IGNjbSBmaXJcclxuYT1ydGNwLWZiOjk2IG5hY2tcclxuYT1ydGNwLWZiOjk2IG5hY2sgcGxpXHJcbmE9cnRwbWFwOjk3IHJ0eC85MDAwMFxyXG5hPWZtdHA6OTcgYXB0PTk2XHJcbmE9cnRwbWFwOjk4IFZQOS85MDAwMFxyXG5hPXJ0Y3AtZmI6OTggZ29vZy1yZW1iXHJcbmE9cnRjcC1mYjo5OCB0cmFuc3BvcnQtY2NcclxuYT1ydGNwLWZiOjk4IGNjbSBmaXJcclxuYT1ydGNwLWZiOjk4IG5hY2tcclxuYT1ydGNwLWZiOjk4IG5hY2sgcGxpXHJcbmE9Zm10cDo5OCBwcm9maWxlLWlkPTBcclxuYT1ydHBtYXA6OTkgcnR4LzkwMDAwXHJcbmE9Zm10cDo5OSBhcHQ9OThcclxuYT1ydHBtYXA6MTAwIFZQOS85MDAwMFxyXG5hPXJ0Y3AtZmI6MTAwIGdvb2ctcmVtYlxyXG5hPXJ0Y3AtZmI6MTAwIHRyYW5zcG9ydC1jY1xyXG5hPXJ0Y3AtZmI6MTAwIGNjbSBmaXJcclxuYT1ydGNwLWZiOjEwMCBuYWNrXHJcbmE9cnRjcC1mYjoxMDAgbmFjayBwbGlcclxuYT1mbXRwOjEwMCBwcm9maWxlLWlkPTJcclxuYT1ydHBtYXA6MTAxIHJ0eC85MDAwMFxyXG5hPWZtdHA6MTAxIGFwdD0xMDBcclxuYT1ydHBtYXA6MzUgVlA5LzkwMDAwXHJcbmE9cnRjcC1mYjozNSBnb29nLXJlbWJcclxuYT1ydGNwLWZiOjM1IHRyYW5zcG9ydC1jY1xyXG5hPXJ0Y3AtZmI6MzUgY2NtIGZpclxyXG5hPXJ0Y3AtZmI6MzUgbmFja1xyXG5hPXJ0Y3AtZmI6MzUgbmFjayBwbGlcclxuYT1mbXRwOjM1IHByb2ZpbGUtaWQ9MVxyXG5hPXJ0cG1hcDozNiBydHgvOTAwMDBcclxuYT1mbXRwOjM2IGFwdD0zNVxyXG5hPXJ0cG1hcDozNyBWUDkvOTAwMDBcclxuYT1ydGNwLWZiOjM3IGdvb2ctcmVtYlxyXG5hPXJ0Y3AtZmI6MzcgdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjozNyBjY20gZmlyXHJcbmE9cnRjcC1mYjozNyBuYWNrXHJcbmE9cnRjcC1mYjozNyBuYWNrIHBsaVxyXG5hPWZtdHA6MzcgcHJvZmlsZS1pZD0zXHJcbmE9cnRwbWFwOjM4IHJ0eC85MDAwMFxyXG5hPWZtdHA6MzggYXB0PTM3XHJcbmE9cnRwbWFwOjEwMiBIMjY0LzkwMDAwXHJcbmE9cnRjcC1mYjoxMDIgZ29vZy1yZW1iXHJcbmE9cnRjcC1mYjoxMDIgdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjoxMDIgY2NtIGZpclxyXG5hPXJ0Y3AtZmI6MTAyIG5hY2tcclxuYT1ydGNwLWZiOjEwMiBuYWNrIHBsaVxyXG5hPWZtdHA6MTAyIGxldmVsLWFzeW1tZXRyeS1hbGxvd2VkPTE7cGFja2V0aXphdGlvbi1tb2RlPTE7cHJvZmlsZS1sZXZlbC1pZD00MjAwMWZcclxuYT1ydHBtYXA6MTAzIHJ0eC85MDAwMFxyXG5hPWZtdHA6MTAzIGFwdD0xMDJcclxuYT1ydHBtYXA6MTA0IEgyNjQvOTAwMDBcclxuYT1ydGNwLWZiOjEwNCBnb29nLXJlbWJcclxuYT1ydGNwLWZiOjEwNCB0cmFuc3BvcnQtY2NcclxuYT1ydGNwLWZiOjEwNCBjY20gZmlyXHJcbmE9cnRjcC1mYjoxMDQgbmFja1xyXG5hPXJ0Y3AtZmI6MTA0IG5hY2sgcGxpXHJcbmE9Zm10cDoxMDQgbGV2ZWwtYXN5bW1ldHJ5LWFsbG93ZWQ9MTtwYWNrZXRpemF0aW9uLW1vZGU9MDtwcm9maWxlLWxldmVsLWlkPTQyMDAxZlxyXG5hPXJ0cG1hcDoxMDUgcnR4LzkwMDAwXHJcbmE9Zm10cDoxMDUgYXB0PTEwNFxyXG5hPXJ0cG1hcDoxMDYgSDI2NC85MDAwMFxyXG5hPXJ0Y3AtZmI6MTA2IGdvb2ctcmVtYlxyXG5hPXJ0Y3AtZmI6MTA2IHRyYW5zcG9ydC1jY1xyXG5hPXJ0Y3AtZmI6MTA2IGNjbSBmaXJcclxuYT1ydGNwLWZiOjEwNiBuYWNrXHJcbmE9cnRjcC1mYjoxMDYgbmFjayBwbGlcclxuYT1mbXRwOjEwNiBsZXZlbC1hc3ltbWV0cnktYWxsb3dlZD0xO3BhY2tldGl6YXRpb24tbW9kZT0xO3Byb2ZpbGUtbGV2ZWwtaWQ9NDJlMDFmXHJcbmE9cnRwbWFwOjEwNyBydHgvOTAwMDBcclxuYT1mbXRwOjEwNyBhcHQ9MTA2XHJcbmE9cnRwbWFwOjEwOCBIMjY0LzkwMDAwXHJcbmE9cnRjcC1mYjoxMDggZ29vZy1yZW1iXHJcbmE9cnRjcC1mYjoxMDggdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjoxMDggY2NtIGZpclxyXG5hPXJ0Y3AtZmI6MTA4IG5hY2tcclxuYT1ydGNwLWZiOjEwOCBuYWNrIHBsaVxyXG5hPWZtdHA6MTA4IGxldmVsLWFzeW1tZXRyeS1hbGxvd2VkPTE7cGFja2V0aXphdGlvbi1tb2RlPTA7cHJvZmlsZS1sZXZlbC1pZD00MmUwMWZcclxuYT1ydHBtYXA6MTA5IHJ0eC85MDAwMFxyXG5hPWZtdHA6MTA5IGFwdD0xMDhcclxuYT1ydHBtYXA6MTI3IEgyNjQvOTAwMDBcclxuYT1ydGNwLWZiOjEyNyBnb29nLXJlbWJcclxuYT1ydGNwLWZiOjEyNyB0cmFuc3BvcnQtY2NcclxuYT1ydGNwLWZiOjEyNyBjY20gZmlyXHJcbmE9cnRjcC1mYjoxMjcgbmFja1xyXG5hPXJ0Y3AtZmI6MTI3IG5hY2sgcGxpXHJcbmE9Zm10cDoxMjcgbGV2ZWwtYXN5bW1ldHJ5LWFsbG93ZWQ9MTtwYWNrZXRpemF0aW9uLW1vZGU9MTtwcm9maWxlLWxldmVsLWlkPTRkMDAxZlxyXG5hPXJ0cG1hcDoxMjUgcnR4LzkwMDAwXHJcbmE9Zm10cDoxMjUgYXB0PTEyN1xyXG5hPXJ0cG1hcDozOSBIMjY0LzkwMDAwXHJcbmE9cnRjcC1mYjozOSBnb29nLXJlbWJcclxuYT1ydGNwLWZiOjM5IHRyYW5zcG9ydC1jY1xyXG5hPXJ0Y3AtZmI6MzkgY2NtIGZpclxyXG5hPXJ0Y3AtZmI6MzkgbmFja1xyXG5hPXJ0Y3AtZmI6MzkgbmFjayBwbGlcclxuYT1mbXRwOjM5IGxldmVsLWFzeW1tZXRyeS1hbGxvd2VkPTE7cGFja2V0aXphdGlvbi1tb2RlPTA7cHJvZmlsZS1sZXZlbC1pZD00ZDAwMWZcclxuYT1ydHBtYXA6NDAgcnR4LzkwMDAwXHJcbmE9Zm10cDo0MCBhcHQ9MzlcclxuYT1ydHBtYXA6NDEgSDI2NC85MDAwMFxyXG5hPXJ0Y3AtZmI6NDEgZ29vZy1yZW1iXHJcbmE9cnRjcC1mYjo0MSB0cmFuc3BvcnQtY2NcclxuYT1ydGNwLWZiOjQxIGNjbSBmaXJcclxuYT1ydGNwLWZiOjQxIG5hY2tcclxuYT1ydGNwLWZiOjQxIG5hY2sgcGxpXHJcbmE9Zm10cDo0MSBsZXZlbC1hc3ltbWV0cnktYWxsb3dlZD0xO3BhY2tldGl6YXRpb24tbW9kZT0xO3Byb2ZpbGUtbGV2ZWwtaWQ9ZjQwMDFmXHJcbmE9cnRwbWFwOjQyIHJ0eC85MDAwMFxyXG5hPWZtdHA6NDIgYXB0PTQxXHJcbmE9cnRwbWFwOjQzIEgyNjQvOTAwMDBcclxuYT1ydGNwLWZiOjQzIGdvb2ctcmVtYlxyXG5hPXJ0Y3AtZmI6NDMgdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjo0MyBjY20gZmlyXHJcbmE9cnRjcC1mYjo0MyBuYWNrXHJcbmE9cnRjcC1mYjo0MyBuYWNrIHBsaVxyXG5hPWZtdHA6NDMgbGV2ZWwtYXN5bW1ldHJ5LWFsbG93ZWQ9MTtwYWNrZXRpemF0aW9uLW1vZGU9MDtwcm9maWxlLWxldmVsLWlkPWY0MDAxZlxyXG5hPXJ0cG1hcDo0NCBydHgvOTAwMDBcclxuYT1mbXRwOjQ0IGFwdD00M1xyXG5hPXJ0cG1hcDo0NSBBVjEvOTAwMDBcclxuYT1ydGNwLWZiOjQ1IGdvb2ctcmVtYlxyXG5hPXJ0Y3AtZmI6NDUgdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjo0NSBjY20gZmlyXHJcbmE9cnRjcC1mYjo0NSBuYWNrXHJcbmE9cnRjcC1mYjo0NSBuYWNrIHBsaVxyXG5hPXJ0cG1hcDo0NiBydHgvOTAwMDBcclxuYT1mbXRwOjQ2IGFwdD00NVxyXG5hPXJ0cG1hcDo0NyBBVjEvOTAwMDBcclxuYT1ydGNwLWZiOjQ3IGdvb2ctcmVtYlxyXG5hPXJ0Y3AtZmI6NDcgdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjo0NyBjY20gZmlyXHJcbmE9cnRjcC1mYjo0NyBuYWNrXHJcbmE9cnRjcC1mYjo0NyBuYWNrIHBsaVxyXG5hPWZtdHA6NDcgcHJvZmlsZT0xXHJcbmE9cnRwbWFwOjQ4IHJ0eC85MDAwMFxyXG5hPWZtdHA6NDggYXB0PTQ3XHJcbmE9cnRwbWFwOjExMiBIMjY0LzkwMDAwXHJcbmE9cnRjcC1mYjoxMTIgZ29vZy1yZW1iXHJcbmE9cnRjcC1mYjoxMTIgdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjoxMTIgY2NtIGZpclxyXG5hPXJ0Y3AtZmI6MTEyIG5hY2tcclxuYT1ydGNwLWZiOjExMiBuYWNrIHBsaVxyXG5hPWZtdHA6MTEyIGxldmVsLWFzeW1tZXRyeS1hbGxvd2VkPTE7cGFja2V0aXphdGlvbi1tb2RlPTE7cHJvZmlsZS1sZXZlbC1pZD02NDAwMWZcclxuYT1ydHBtYXA6MTEzIHJ0eC85MDAwMFxyXG5hPWZtdHA6MTEzIGFwdD0xMTJcclxuYT1ydHBtYXA6MTE0IEgyNjQvOTAwMDBcclxuYT1ydGNwLWZiOjExNCBnb29nLXJlbWJcclxuYT1ydGNwLWZiOjExNCB0cmFuc3BvcnQtY2NcclxuYT1ydGNwLWZiOjExNCBjY20gZmlyXHJcbmE9cnRjcC1mYjoxMTQgbmFja1xyXG5hPXJ0Y3AtZmI6MTE0IG5hY2sgcGxpXHJcbmE9Zm10cDoxMTQgbGV2ZWwtYXN5bW1ldHJ5LWFsbG93ZWQ9MTtwYWNrZXRpemF0aW9uLW1vZGU9MDtwcm9maWxlLWxldmVsLWlkPTY0MDAxZlxyXG5hPXJ0cG1hcDoxMTUgcnR4LzkwMDAwXHJcbmE9Zm10cDoxMTUgYXB0PTExNFxyXG5hPXJ0cG1hcDoxMTYgcmVkLzkwMDAwXHJcbmE9cnRwbWFwOjExNyBydHgvOTAwMDBcclxuYT1mbXRwOjExNyBhcHQ9MTE2XHJcbmE9cnRwbWFwOjExOCB1bHBmZWMvOTAwMDBcclxuYT1ydHBtYXA6NDkgZmxleGZlYy0wMy85MDAwMFxyXG5hPXJ0Y3AtZmI6NDkgZ29vZy1yZW1iXHJcbmE9cnRjcC1mYjo0OSB0cmFuc3BvcnQtY2NcclxuYT1mbXRwOjQ5IHJlcGFpci13aW5kb3c9MTAwMDAwMDBcclxuIn0=`
	signal.Decode(sd, &offer)

	// Create a new RTCPeerConnection
	h264Params, err := openh264.NewParams()
	if err != nil {
		panic(err)
	}
	h264Params.BitRate = 500_000 // 500kbps

	opusParams, err := opus.NewParams()
	if err != nil {
		panic(err)
	}
	codecSelector := mediadevices.NewCodecSelector(
		mediadevices.WithVideoEncoders(&h264Params),
		mediadevices.WithAudioEncoders(&opusParams),
	)

	mediaEngine := webrtc.MediaEngine{}
	codecSelector.Populate(&mediaEngine)
	logger.Info("peer connecting")
	api := webrtc.NewAPI(webrtc.WithMediaEngine(&mediaEngine))
	peerConnection, err := api.NewPeerConnection(config)
	if err != nil {
		panic(err)
	}

	logger.Info("peer connected")

	// Set the handler for ICE connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		fmt.Printf("Connection State has changed %s \n", connectionState.String())
	})

	s, err := mediadevices.GetUserMedia(mediadevices.MediaStreamConstraints{
		Video: func(c *mediadevices.MediaTrackConstraints) {
			c.FrameFormat = prop.FrameFormat(frame.FormatI420)
			c.Width = prop.Int(640)
			c.Height = prop.Int(480)
		},
		Audio: func(c *mediadevices.MediaTrackConstraints) {
		},
		Codec: codecSelector,
	})
	if err != nil {
		panic(err)
	}

	logger.Info("get user media")

	for _, track := range s.GetTracks() {
		track.OnEnded(func(err error) {
			fmt.Printf("Track (ID: %s) ended with error: %v\n",
				track.ID(), err)
		})

		_, err = peerConnection.AddTransceiverFromTrack(track,
			webrtc.RtpTransceiverInit{
				Direction: webrtc.RTPTransceiverDirectionSendonly,
			},
		)
		if err != nil {
			panic(err)
		}
	}

	// Set the remote SessionDescription
	err = peerConnection.SetRemoteDescription(offer)
	if err != nil {
		panic(err)
	}

	// Create an answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	// Create channel that is blocked until ICE Gathering is complete
	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)

	// Sets the LocalDescription, and starts our UDP listeners
	err = peerConnection.SetLocalDescription(answer)
	if err != nil {
		panic(err)
	}

	// Block until ICE Gathering is complete, disabling trickle ICE
	// we do this because we only can exchange one signaling message
	// in a production application you should exchange ICE Candidates via OnICECandidate
	<-gatherComplete

	// Output the answer in base64 so we can paste it in browser
	fmt.Println(signal.Encode(*peerConnection.LocalDescription()))

	// Block forever
	select {}
}
